### ISSUE TITLE
Replace image should be incorporated.

### ISSUE THREAD

**Issue by jasimawan** [aspect-apps/react-native-images-collage#15]

**Comment by lukebrandonfarrell** [comment]
@jasimawan Thanks for the request. We plan to incorporate replace and resize in the next few months. What would you have in mind for the replace API, something like `ref.replace([1, 0], "url")` ?

**Comment by jasimawan** [comment]
Thanks for the quick response @lukebrandonfarrell. 
What I have in mind was to implement a "shortPress" on the every image just like "longPress" and when user will press any image, he/she can select the image from gallery or a local image, and then replace it using your logic "ref.replace([1, 0], "url")" ...

**Comment by harbolaez** [comment]
Hi - any update or progress on this?

**Comment by lukebrandonfarrell** [comment]
@harbolaez I don't think replace image should be directly incorporated into this library. What we could do instead is allow custom callbacks for onPress, onLongPress, onPressIn and oPressOut. This should be a fairly simple PR if you wish to contribute.

**Comment by jasimawan** [comment]
I forked your library 6 months ago and I added a custom absolute button into the library which then I used to replace the respective image. I can contribute in the library and can request a merge pull request but for that firstly I have to pull the latest library and then I will implement the changes. After that I will request to merge. @lukebrandonfarrell

**Comment by lukebrandonfarrell** [comment]
@jasimawan 

If we are going to go the direction if the button, there should be simple props which allow you to customise the button component and position. i.e.

```js
<DynamicCollage
       onEditButtonPress={/*custom action*/}
       editButtonPosition="top-left|top-right|bottom-left|bottom-right"
       EditButtonComponent={<MyCustomEditButton />}
/>
```

Let me know what you think

**Comment by jasimawan** [comment]
Yes, You are right. It will be a better approach and give developer the flexibility to implement his/her own custom button. Let me know if you will implement yourself or I do it and send you the merge pull request ? 
@lukebrandonfarrell

**Comment by lukebrandonfarrell** [comment]
@jasimawan Send a PR and can help contribute if needed

**Comment by harbolaez** [comment]
thanks, guys -- looking forward to this. Let me know if I can help with anything.

**Comment by lukebrandonfarrell** [comment]
@harbolaez Why would you want the image itself to be clickable? i.e. do you mean like a selectable state ? Maybe `onFocus`  and we apply a custom style `imageFocussedStyle`

**Comment by harbolaez** [comment]
@lukebrandonfarrell yeah - a selectable state.

**Comment by lukebrandonfarrell** [comment]
@harbolaez That might be a good first PR if you are interested ? I guess it would be an `onFocus` callback when image is pressed (short pressed) and some `isFocusses` state which is tracked in the library which applies the `imageFocussedStyle` when `true` for that image

**Comment by jasimawan** [comment]
I implemented it and sending you the PR. @lukebrandonfarrell
