### ISSUE TITLE
edit button

### ISSUE THREAD

**Issue by antoinefotso** [aspect-apps/react-native-images-collage#26]
Edit button not show.
i set editButtonVisible to true , noting show , i tried exemple but still no edit button

**Comment by lukebrandonfarrell** [comment]
Did you resolve this?

**Comment by antoinefotso** [comment]
@lukebrandonfarrell , no I didn't .
It was not really important feature for me.
You can open a new  issue, or edit the source code, it's pretty easy to understand and restyle.

**Comment by lukebrandonfarrell** [comment]
@antoinefotso What was the issue? Could you give us more details?

@jasimawan Just added this feature so strange that it is broke. Possibly usage is not clear? Have you enabled `isEditButtonVisible` to `true`?

**Comment by jasimawan** [comment]
I just checked it and `isEditButtonVissible` is working as expected. Maybe he is doing something wrong. 
@lukebrandonfarrell
