### ISSUE TITLE
Animated: ‘useNativeDriver’ was not specified.

### ISSUE THREAD

**Issue by mar-alsharif** [aspect-apps/react-native-images-collage#27]
I get a warning about the useNativeDriver as it has to be explicitly set to true or false.

**Comment by lukebrandonfarrell** [comment]
@mar-alsharif Would you be able to find the line in question? and possibly make a PR?

**Comment by mar-alsharif** [comment]
I think it’s alright now. Bu I have a request if possible. It would be helpful if you can put a dynamic example not based on class components but rather on functional components

**Comment by lukebrandonfarrell** [comment]
@mar-alsharif What do you mean? "Dynamic Example", could you elaborate?

**Comment by mar-alsharif** [comment]
Like I want the matrix to be defined dynamically and not being hard coded, but I don’t know how to do that

**Comment by lukebrandonfarrell** [comment]
@mar-alsharif If you contact me privately on Discord (https://discord.gg/QqTN6HqNTG) we are running a workshop
